### ISSUE TITLE
exit status 2

### ISSUE THREAD

**Issue by nmc-ei** [ExaScience/elprep#50]
Hi,
I run elprep. However I couldn't get a vcf file.

```
$ elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --sorting-order coordinate --bqsr Sample.output.recal --known-sites dbsnp_138.hg19.elsites,Mills_and_1000G_gold_standard.indels.hg19.elsites --reference ucsc.hg19.elfasta --haplotypecaller Sample.output.vcf.gz

elprep version 5.0.2 compiled with go1.16.4 - see http://github.com/exascience/elprep for more information.

2021/06/30 19:13:41 Created log file at /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-13-41-430755928-JST.log
2021/06/30 19:13:41 Command line: [elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --sorting-order coordinate --bqsr Sample.output.recal --known-sites dbsnp_138.hg19.elsites,Mills_and_1000G_gold_standard.indels.hg19.elsites --reference ucsc.hg19.elfasta --haplotypecaller Sample.output.vcf.gz]
2021/06/30 19:13:41 Executing command:
 elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites dbsnp_138.hg19.elsites,Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam
2021/06/30 19:13:41 Splitting...
2021/06/30 19:15:39 Filtering (phase 1)...
2021/06/30 19:16:46 exit status 2
```

best and thanks for this utility,

eisuke

**Comment by caherzee** [comment]
Hi Eisuke,

Would it be possible to list the contents of the detailed log file: /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-13-41-430755928-JST.log ?

It may show more details why the run is failing.

Thanks a lot!

Kind regards,
Charlotte

**Comment by nmc-ei** [comment]
Thank you.

I was able to check the log file. However I couldn't understand why the run is failing.
```
elprep version 5.0.2 compiled with go1.16.4 - see http://github.com/exascience/elprep for more information.

2021/06/30 19:13:41 Created log file at /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-13-41-430755928-JST.log
2021/06/30 19:13:41 Command line: [elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --sorting-order coordinate --bqsr Sample.output.recal --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --haplotypecaller Sample.output.vcf.gz]
2021/06/30 19:13:41 Executing command:
 elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam
2021/06/30 19:13:41 Splitting...

elprep version 5.0.2 compiled with go1.16.4 - see http://github.com/exascience/elprep for more information.

2021/06/30 19:13:41 Created log file at /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-13-41-503296045-JST.log
2021/06/30 19:13:41 Command line: [elprep split Sample.Aligned.sortedByCoord.out.bam /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/ --output-prefix Sample.Aligned.sortedByCoord.out --output-type bam]
2021/06/30 19:13:41 Executing command:
 elprep split Sample.Aligned.sortedByCoord.out.bam /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/ --output-prefix Sample.Aligned.sortedByCoord.out --output-type bam
2021/06/30 19:15:39 Filtering (phase 1)...

elprep version 5.0.2 compiled with go1.16.4 - see http://github.com/exascience/elprep for more information.

2021/06/30 19:15:39 Created log file at /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-15-39-769846713-JST.log
2021/06/30 19:15:39 Command line: [elprep filter /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/splits/Sample.Aligned.sortedByCoord.out-group00010.bam /home/nmc-ei/development/elprep/elprep-splits-processed-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00010.bam --mark-duplicates --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --sorting-order coordinate --pg-cmd-line elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam --bqsr-tables-only /home/nmc-ei/development/elprep/elprep-tabs-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00010.bam.elrecal --mark-optical-duplicates-intermediate /home/nmc-ei/development/elprep/elprep-metrics-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00010.bam --optical-duplicates-pixel-distance 100]
2021/06/30 19:15:39 Executing command:
 elprep filter /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/splits/Sample.Aligned.sortedByCoord.out-group00010.bam /home/nmc-ei/development/elprep/elprep-splits-processed-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00010.bam --mark-duplicates --mark-optical-duplicates-intermediate /home/nmc-ei/development/elprep/elprep-metrics-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00010.bam --optical-duplicates-pixel-distance 100 --bqsr-tables-only /home/nmc-ei/development/elprep/elprep-tabs-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00010.bam.elrecal --max-cycle 500 --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --sorting-order coordinate --pg-cmd-line elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam

elprep version 5.0.2 compiled with go1.16.4 - see http://github.com/exascience/elprep for more information.

2021/06/30 19:15:53 Created log file at /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-15-53-699365174-JST.log
2021/06/30 19:15:53 Command line: [elprep filter /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/splits/Sample.Aligned.sortedByCoord.out-group00012.bam /home/nmc-ei/development/elprep/elprep-splits-processed-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00012.bam --mark-duplicates --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --sorting-order coordinate --pg-cmd-line elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam --bqsr-tables-only /home/nmc-ei/development/elprep/elprep-tabs-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00012.bam.elrecal --mark-optical-duplicates-intermediate /home/nmc-ei/development/elprep/elprep-metrics-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00012.bam --optical-duplicates-pixel-distance 100]
2021/06/30 19:15:53 Executing command:
 elprep filter /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/splits/Sample.Aligned.sortedByCoord.out-group00012.bam /home/nmc-ei/development/elprep/elprep-splits-processed-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00012.bam --mark-duplicates --mark-optical-duplicates-intermediate /home/nmc-ei/development/elprep/elprep-metrics-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00012.bam --optical-duplicates-pixel-distance 100 --bqsr-tables-only /home/nmc-ei/development/elprep/elprep-tabs-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00012.bam.elrecal --max-cycle 500 --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --sorting-order coordinate --pg-cmd-line elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam

elprep version 5.0.2 compiled with go1.16.4 - see http://github.com/exascience/elprep for more information.

2021/06/30 19:16:23 Created log file at /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-16-23-899797969-JST.log
2021/06/30 19:16:23 Command line: [elprep filter /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/splits/Sample.Aligned.sortedByCoord.out-group00001.bam /home/nmc-ei/development/elprep/elprep-splits-processed-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00001.bam --mark-duplicates --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --sorting-order coordinate --pg-cmd-line elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam --bqsr-tables-only /home/nmc-ei/development/elprep/elprep-tabs-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00001.bam.elrecal --mark-optical-duplicates-intermediate /home/nmc-ei/development/elprep/elprep-metrics-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00001.bam --optical-duplicates-pixel-distance 100]
2021/06/30 19:16:23 Executing command:
 elprep filter /home/nmc-ei/development/elprep/elprep-splits-5c6bcc74-1106-402b-a5e0-ee27020101d7/splits/Sample.Aligned.sortedByCoord.out-group00001.bam /home/nmc-ei/development/elprep/elprep-splits-processed-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00001.bam --mark-duplicates --mark-optical-duplicates-intermediate /home/nmc-ei/development/elprep/elprep-metrics-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00001.bam --optical-duplicates-pixel-distance 100 --bqsr-tables-only /home/nmc-ei/development/elprep/elprep-tabs-5c6bcc74-1106-402b-a5e0-ee27020101d7/Sample.Aligned.sortedByCoord.out-group00001.bam.elrecal --max-cycle 500 --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --sorting-order coordinate --pg-cmd-line elprep sfm Sample.Aligned.sortedByCoord.out.bam Sample.output.bam --mark-duplicates --mark-optical-duplicates Sample.output.metrics --optical-duplicates-pixel-distance 100 --bqsr Sample.output.recal --reference /home/nmc-ei/elprep/ucsc.hg19.elfasta --quantize-levels 0 --max-cycle 500 --known-sites /home/nmc-ei/elprep/dbsnp_138.hg19.elsites,/home/nmc-ei/elprep/Mills_and_1000G_gold_standard.indels.hg19.elsites --haplotypecaller Sample.output.vcf.gz --sorting-order coordinate --intermediate-files-output-prefix Sample.Aligned.sortedByCoord.out --intermediate-files-output-type bam
2021/06/30 19:16:46 exit status 2
panic: exit status 2

goroutine 1 [running]:
log.Panic(0xc00018f138, 0x1, 0x1)
	/opt/conda/conda-bld/elprep_1621499891924/_build_env/go/src/log/log.go:354 +0xae
github.com/exascience/elprep/v5/internal.RunCmd(0xc00023e840)
	/opt/conda/conda-bld/elprep_1621499891924/work/internal/misc.go:41 +0x78
github.com/exascience/elprep/v5/cmd.Sfm()
	/opt/conda/conda-bld/elprep_1621499891924/work/cmd/sfm.go:682 +0x7a7e
main.main()
	/opt/conda/conda-bld/elprep_1621499891924/work/main.go:81 +0x20c

```

**Comment by caherzee** [comment]
Hi,

Could it be possible to also check the detailed log /home/nmc-ei/logs/elprep/elprep-2021-06-30-19-16-23-899797969-JST.log ? The sfm command splits the input into several smaller files that are processed one by one. It seems that the command fails when processing group 1. 

Thanks,
Charlotte

**Comment by nmc-ei** [comment]
Thank you.

I attach a file because it is long.

[elprep-2021-06-30-19-16-23-899797969-JST.log](https://github.com/ExaScience/elprep/files/6768769/elprep-2021-06-30-19-16-23-899797969-JST.log)

**Comment by caherzee** [comment]
Hi,

The error log reports an out of memory error after allocating around 19GB of RAM.

Is it possible to test your job on a machine with more RAM?

The amount of RAM needed depends on the size of your input files. Also see "Memory Requirements" in the README.

Thanks a lot for testing!
Charlotte

**Comment by nmc-ei** [comment]
Thank you very much.

If I can get more RAM, I will try.
